# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:alpine

# Set working directory
WORKDIR /app

# Copy all files
COPY . .

# Install dependencies using bun
RUN bun install

# Expose port if necessary (MCP uses stdio, so this might not be needed)

# Start the MCP server
CMD ["bun", "src/index.ts"]
